"""Export test cases to Markdown format using Jinja2 templates."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, BaseLoader

from testgen.config import GenerationResult


MARKDOWN_TEMPLATE = """\
# Test Cases Report

**Generated:** {{ generated_date }}
**Session:** {{ session_id }}
**Total Test Cases:** {{ summary.total }}
**Requirements Covered:** {{ summary.requirements_count }}

---

## Summary

### By Priority

| Priority | Count |
|----------|-------|
{% for priority, count in summary.by_priority.items() -%}
| {{ priority }} | {{ count }} |
{% endfor %}

### By Type

| Type | Count |
|------|-------|
{% for type, count in summary.by_type.items() -%}
| {{ type }} | {{ count }} |
{% endfor %}

### By ISTQB Technique

| Technique | Count |
|-----------|-------|
{% for technique, count in summary.by_technique.items() -%}
| {{ technique }} | {{ count }} |
{% endfor %}

---

## Test Cases Overview

| ID | Title | Priority | Type | Technique | Traceability |
|----|-------|----------|------|-----------|--------------|
{% for tc in test_cases -%}
| {{ tc.id }} | {{ tc.title }} | {{ tc.priority }} | {{ tc.type }} | {{ tc.istqb_technique }} | {{ tc.traceability }} |
{% endfor %}

---

## Detailed Test Cases

{% for tc in test_cases %}
### {{ tc.id }}: {{ tc.title }}

- **Priority:** {{ tc.priority }}
- **Type:** {{ tc.type }}
- **ISTQB Technique:** {{ tc.istqb_technique }}
- **Traceability:** {{ tc.traceability }}

**Preconditions:**
{{ tc.preconditions }}

**Steps:**
{% for step in tc.steps %}
{% if step_format == 'step_expected' -%}
{{ loop.index }}. **Step:** {{ step.step }}
   **Expected:** {{ step.expected }}
{% else -%}
{{ loop.index }}. **Given:** {{ step.given }}
   **When:** {{ step.when }}
   **Then:** {{ step.then }}
{% endif -%}
{% endfor %}

**Test Data:**
`{{ tc.test_data }}`

**Expected Result:**
{{ tc.expected_result }}

---

{% endfor %}

## Traceability Matrix

| Requirement | Test Cases |
|-------------|------------|
{% for req_id, tc_ids in traceability.items() -%}
| {{ req_id }} | {{ tc_ids | join(", ") }} |
{% endfor %}

---

*Generated by TestGen v1.0.0*
"""


def export_markdown(result: GenerationResult, output_path: str | Path) -> Path:
    """Export generation result to a Markdown file.

    Args:
        result: The generation result containing test cases.
        output_path: Path for the output Markdown file.

    Returns:
        Path to the created file.
    """
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    content = render_markdown(result)
    path.write_text(content, encoding="utf-8")
    return path


def render_markdown(result: GenerationResult) -> str:
    """Render the Markdown content from a generation result."""
    env = Environment(loader=BaseLoader(), autoescape=False)
    template = env.from_string(MARKDOWN_TEMPLATE)

    traceability = _build_traceability_map(result)

    return template.render(
        generated_date=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        session_id=result.session_id,
        summary=result.summary,
        test_cases=[tc.to_dict() for tc in result.test_cases],
        traceability=traceability,
        step_format=result.step_format,
    )


def _build_traceability_map(result: GenerationResult) -> dict[str, list[str]]:
    """Build a requirement -> test cases mapping."""
    mapping: dict[str, list[str]] = {}
    for tc in result.test_cases:
        req_id = tc.traceability
        if req_id not in mapping:
            mapping[req_id] = []
        mapping[req_id].append(tc.id)
    return mapping
